### ISSUE TITLE
转化时报错 AttributeError: module 'PyPDF2' has no attribute 'PdfReader'

### ISSUE THREAD

**Issue by EsunR** [Nagi-ovo/Xuexin-Converter#1]
完整报错如下，辛苦看下是什么问题：

```
AttributeError
AttributeError: module 'PyPDF2' has no attribute 'PdfReader'

Traceback (most recent call last)
File "/Users/x/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/x/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
response = self.handle_exception(e)
File "/Users/x/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "/Users/x/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/x/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/x/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/Users/x/Desktop/CHSI-Converter/app.py", line 84, in convert_file
output_path = convert_to_docx(filepath)
File "/Users/x/Desktop/CHSI-Converter/app.py", line 23, in convert_to_docx
extracted_info = extract_info_from_pdf(path)
File "/Users/x/Desktop/CHSI-Converter/extract_info.py", line 76, in extract_info_from_pdf
text = extract_text_from_pdf(path)
File "/Users/x/Desktop/CHSI-Converter/extract_info.py", line 8, in extract_text_from_pdf
pdf_reader = PyPDF2.PdfReader(pdf_file_obj)
AttributeError: module 'PyPDF2' has no attribute 'PdfReader'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

**Comment by EsunR** [comment]
把 PyPDF2 替换为 pypdf 并安装好 poppler 后可以成功使用，但是翻译出的结果只有姓名，其他的信息都没有展示出来
![](https://esunr-image-bed.oss-cn-beijing.aliyuncs.com/picgo/202311171355861.png)

**Comment by EsunR** [comment]
fixed: https://github.com/Nagi-ovo/CHSI-Converter/pull/2
