### ISSUE TITLE
Offline 运行 main.py 报错 缺少 poppler

### ISSUE THREAD

**Issue by Tunglies** [Nagi-ovo/Xuexin-Converter#6]
```
PS C:\Users\User\Downloads\CHSI-Converter> python .\main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pdf2image\pdf2image.py", line 568, in pdfinfo_from_path
    proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\CHSI-Converter\main.py", line 116, in convert_to_docx
    cropped_image_1 = extract_image_from_pdf(path, 1, 1898, 583, 2230, 1026)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\CHSI-Converter\extract_img.py", line 5, in extract_image_from_pdf
    images = convert_from_path(path, dpi=300, first_page=page_number, last_page=page_number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pdf2image\pdf2image.py", line 127, in convert_from_path
    page_count = pdfinfo_from_path(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pdf2image\pdf2image.py", line 594, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

需要额外安装 poppler，文档中并未提及。

**Comment by Nagi-ovo** [comment]
Thanks for the feedback :)
确实有这个问题。我在Mac系统调试的时候遇到过，但是印象中不记得windows环境中有装过，因此以为这是win自带的...
